### PR TITLE
Added rPI-2 support (arm7)

### PR DESCRIPTION
**Pull request by gergely-marko**

### CODE REVIEW

**Comment by javruben** [comment]
Wouldn't this line, still stop the script: https://github.com/c9/install/pull/25/files#diff-3fbb47e318cd8802bd325e7da9aaabe8R63 ?

**Comment by gergely-marko** [comment]
Well, it did not stopped the process by me.

2015-02-15 23:12 GMT+01:00 Ruben Daniels <notifications@github.com>:

**Comment by javruben** [comment]
Ok, merging. Would you mind verifying the change on your PI?

**Comment by gergely-marko** [comment]
Sure. I make a new install.


2015-02-15 23:17 GMT+01:00 Ruben Daniels <notifications@github.com>:

**Comment by gergely-marko** [comment]
Hi again,

you were right about line #63 in install.sh

I forked install, modified the script and started a new clean build,
referencing to install.sh of my fork.

Install seems ok now, took about one hour in my setup.

The build process did take a lot longer as before. When I had a local copy
of install.sh, and the file scripts/install-sdk.sh was referencing to it,
the build process was quicker, but reulted with Success! as well.
I think a lot of modules were not built/installed. But the IDE was running
and seemed to be wroking properly at first.

Just for info, I have a fresh build of node.js, v 0.12. I modified the
configuration to build with armv7.


I created a PR again.

cheers,
Gergely Markó

**Comment by javruben** [comment]
Interesting. We have tested with Node 0.10.26. We are still working on 0.12
support.

**Pull request merged**
